### PR TITLE
Adding IstioLifecycleManager and GatewayLifecycleManager to gloo-gateway

### PR DESCRIPTION
**Pull request by nickschuetz**
Added IstioLifecycleManager and GatewayLifecycleManager
Added meshctl check
fixed WAFPolicy syntax error

### CODE REVIEW

**Comment by ably77** [comment]
I just ran through this PR and it worked 👍 

Couple nice to haves:

1. For ILCM deployment, would be nice to review ILCM features and benefits (the why) before deploying so that users can understand the complexity that we are abstracting from their workflow

2. Will there be a follow up on revision based upgrade for ILCM? Would this require us to move away from using the `istio-injection=enabled` to a revision based tag?

**Review by millerjem — APPROVED** [review]
The only oddity was around the rate-limiting. My first attempt should have allowed 3 request per the configuration. However, only one completed successfully before rate-limiting was apply. Maybe a bug?

**Comment by nickschuetz** [comment]
> The only oddity was around the rate-limiting. My first attempt should have allowed 3 request per the configuration. However, only one completed successfully before rate-limiting was apply. Maybe a bug?

online-boutique has a load generator as a part of the app. I wonder if that is what caused the other 2 hits?

**Comment by nmnellis** [comment]
yes it is^^

**Comment by nmnellis** [comment]
i dont tell customers about it though, no one has caught me yet

**Comment by nickschuetz** [comment]
> 

1. We can maybe leave that for the instructor for now and put that as a TODO for later?
2. Using the default tagging route we can continue to enhance on this when/if we introduce upgrades into the workshop perhaps. The reason hard coded revs were left out was a request from @rvennam to reduce chance for human error and complexity.

**Comment by nickschuetz** [comment]
> 




1. We can maybe leave that for the instructor for now and put that as a TODO for later?
2. Using the default tagging route we can continue to enhance on this when/if we introduce upgrades into the workshop perhaps. The reason hard coded revs were left out was a request from @rvennam to reduce chance for human error and complexity.

@ably77

**Review by ably77 — APPROVED** [review]
LGTM

**Pull request merged**
